### ISSUE TITLE
Pearson Wounding: Bugs and Features

### ISSUE THREAD

**Issue by Incomitatum** [DogsoftheState/mcc_sandbox#23]
I just rewatched the video as I was editing it. Here are the issues.

1: We need it so that the bar comes back. After I healed Ochoa the first time, the bars were gone for the rest of the night: all healing was instant.

2: We went down a lot. This is due to our play needing to get better. Not being pulled out of the fight is nice. Only a couple of us died, one was a bug, and the other bled out.

2a: We need a way (once the bar is working again) to count, per player, how many times they have done down. That then needs to be a multiplier; one that increases the time it takes to get them up. Imagine this as them having more and more holes in them. The medic right now CAN work miracles.

2b: Lets say the normal time to get someone up is 30 seconds. Then, I think you have said, this is increased by how much damage they have taken, PLUS a random-integer. Maybe that (damage taken) could be the damage-taken-over-their-lifetime.

**Comment by chessmaster42** [comment]
1 - Fixed in 93290b703b8b67d864f0f85ace1c33e81c9c5b44
2 - This will be much different with the wounding overhaul in 93290b703b8b67d864f0f85ace1c33e81c9c5b44
2a - This is done in 93290b703b8b67d864f0f85ace1c33e81c9c5b44. An additional 5 seconds is added to future revives every time a unit is brought back. This is reset on death.
2b - Time for revive is 5-60 seconds depending on damage in 93290b703b8b67d864f0f85ace1c33e81c9c5b44. The penalty in 2a is added on top of this
